WebSite/Areas/Trains/Controllers/DccController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.ViewModels;
using AutoMapper;

namespace WebSite.Areas.Trains.Controllers
{
    public class DccController : Controller
    {
        [HandleError]
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult DecoderDescription()
        {
            return View();
        }

        public ActionResult StayALive() => View();

        public ActionResult ElectroFrog() => View();

        public ActionResult DccDecoderDetails(int identifier) => View(new DccDecoderVM().Generate(identifier));

    }
}

WebSite/Areas/Trains/Views/Dcc/DccDecoderDetails.cshtml
@model WebSite.ViewModels.DccDecoderVM

@{
    ViewBag.Title = "DccDecoderDetails";
}

<h2>DccDecoderDetails</h2>

@Html.Partial("_DccDecoder")

WebSite/Areas/Trains/Views/Dcc/DecoderDescription.cshtml
@{
    ViewBag.Title = "DecoderDescription";
}

<link href="~/Scripts/jquery.qtip.css" rel="stylesheet" />
<script src="~/Scripts/jquery.qtip.js"></script>

<script>

    $(function () { 
    
        var qtip = $('[data-tooltip!=""]').qtip({
            content: { attr: 'data-tooltip' },
            style: { classes: 'qtip-bootstrap' },
            position: { my:'left center'}
        });
    })

</script>

<div class="container">

    @section Header {
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h2>DCC Decoder</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="pull-right">
                    @Html.ActionLink("Electrofrog", "Electrofrog", "Dcc", new { area = "Trains" }, new { @class = "btn btn-info btn-md" })
                    @Html.ActionLink("Stay A Live", "StayALive", "Dcc", new { area = "Trains" }, new { @class = "btn btn-info btn-md" })
                    @Html.ActionLink("Decoders", "DecoderDescription", "Dcc", new { area = "Trains" }, new { @class = "btn btn-info btn-md" })
                </div>
            </div>
        </div>
        <hr />
    }

    @section MainBody {

        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                <h3>Decoders</h3>
                <ul>
                    <li>Description</li>
                    <li>@Html.ActionLink("Hornby", "DccDecoderDetails", "Dcc", new { area = "Trains" , identifier = 1 },null )</li>
                    <li>@Html.ActionLink("Bachmann 36-353", "DccDecoderDetails", "Dcc", new { area = "Trains", identifier = 2 }, null)</li>
                    <li>Bachmanns</li>
                    <li>@Html.ActionLink("Lais Ver 1", "DccDecoderDetails", "Dcc", new { area = "Trains", identifier = 4 }, null)</li>
                    <li>@Html.ActionLink("Lais Ver 2", "DccDecoderDetails", "Dcc", new { area = "Trains", identifier = 5 }, null)</li>
                    <li>@Html.ActionLink("GaugeMaster", "DccDecoderDetails", "Dcc", new { area = "Trains", identifier = 8 }, null)</li>
                </ul>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <!-- locomotives -->
                <div id="Wrapper-dccDecoders">
                    <div class="row">
                        <div class="col-lg-12">
                            <h4>Decoder</h4>
                        </div>
                    </div>

                    <hr />

                    <div>
                        <div class="col-lg-12">
                            <h4>Wiring 8 Pin</h4>
                        </div>
                        <div class="col-lg-4">
                            <ol>
                                <li>Motor (+)</li>
                                <li>Rear lights</li>
                                <li>Aux</li>
                                <li>Track feed (-)</li>
                                <li>Motor (-).</li>
                                <li>Front lights</li>
                                <li>Common +ve</li>
                                <li>Track feed (+).</li>
                            </ol>
                        </div>
                        <div class="col-lg-4">
                            <img src="~/Content/Images/Trains/8PinSocket.PNG" width="140" height="200"/>
                        </div>
                    </div>

                    <hr />

                    <div class="row">
                        <div class="col-lg-12">
                            <p>Decoders receive commands from throttles or other devices and are responsible for controlling the motor and/or performing certain functions around a layout.</p>
                            <p>Decoders can be grouped into two main categories, mobile and stationary. Mobile decoders are usually installed in locomotives. Stationary decoders are normally mounted on the layout in a "stationary" position. Stationary decoders can be used to control railway switches, structure lights, scene lighting, animation, and signaling.</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <h4>Configuration Variables.</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <p>
                                A Configuration Variable (CV) is a memory location in a decoder that controls its behavior. Once set, the value will be retained unless the memory is changed or becomes corrupted.
                            </p>
                            <p>
                                The decoder’s address, motor control, lights, sound, and other functions of the locomotive. This is achieved by editing the CVs in the decoder. Some CVs use values ranging from 0 to 255, others use their space in the decoder's memory as a bank of eight on/off switches.
                                A decoder can be programmed changing the basic "factory default" CV settings. Computer software is available which simplifies the programming of decoders.
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <h4>Basic Configuration Variables.</h4>
                        </div>
                    </div>
                    <div class="row">
                        @Html.Partial("_CVValues")
                    </div>
                </div>
            </div>
        </div>

    }

    @section Footer {
        <footer>
            <div class="row">

            </div>
            <div>&copy; DDM Trains 2017</div>
        </footer>
    }

</div>

WebSite/Areas/Trains/Views/Dcc/Electrofrog.cshtml
@{
    ViewBag.Title = "Electrofrog";
}

<h2>Electrofrog</h2>

<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">

    </div>

    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
        <img src="~/Content/Images/Trains/TurnoutModifiedElectrofrog.gif" />
    </div>
</div>

WebSite/Areas/Trains/Views/Dcc/StayAlive.cshtml
@{
    ViewBag.Title = "StayAlive";
}

<h2>StayAlive</h2>

<div class="row">

    <div class="col-md-12">
       <p>Stay a live circuit is particularly helpful with locomotives without multiple pickups or 0-6-0, 0-4-0 wheel arrangements. Allowing them to negoiate dead stops on the track by providing a very short burst of power to the decoder thus keeping the locomotive moving.</p>
    </div>

    <div class="col-md-6 col-sm-12">
        <h4>Typical stay a live circuit</h4>
        <img src="~/Content/Images/Trains/stayALiveCircuit.jpeg" />
    </div>

    <div class="col-md-6 col-sm-12">
        
        <p>The 'capacity' of the capacitor is measured in micofarads (uf). The higher the capacity (more microfarads), the more energy is stored. The more energy stored the longer the loco will run without the dcc signal/power, thus enabling it to negoiate larger deadspots with stalling.</p>
        <p> Using 1000uf, allows two small 470uf capacitors wired in parallel</p>
        <br />
        <p></p>
        <p>The resistor should be half watt with the value determined by the capacitor size, upto 2200uf a 100ohms.</p>
        <p>A diode type 1N4001</p>
    </div>

</div>

WebSite/Areas/Trains/Views/Dcc/_CV29Configurations.cshtml
<h2>CV 29 Configuration</h2>

WebSite/Areas/Trains/Views/Dcc/_CVValues.cshtml
<!-- cv values -->

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <table class="table-striped table">
        <thead style="font-weight:bold; margin:2px; padding:2px; background-color:lightblue;">
            <tr>
                <td style="width:30%">CV Name</td>
                <td style="width:10%">CV #</td>
                <td style="width:20%">Reqd</td>
                <td style="width:40%">Comment</td>
            </tr>
        </thead>
        <tbody>
            <tr id="LocoRow-A">
                <td data-tooltip="The range of addresses available on a DCC system.">Primary Address</td>
                <td>1</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="Controls the minimum voltage applied to the motor on speed step 1">Vstart</td>
                <td>2</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Acceleration Rate</td>
                <td>3</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Deceleration Rate</td>
                <td>4</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="Controls the voltage applied to the motor at maximum throttle.">VHigh</td>
                <td>5</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="Controls the voltage applied to the motor at the mid point of the throttle setting.">VMid</td>
                <td>6</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Manufacturer Version No.</td>
                <td>7</td>
                <td>Yes</td>
                <td>Manufacturer defined version information</td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Manufacturer ID.</td>
                <td>8</td>
                <td>Yes</td>
                <td>Value assigned by NMRA</td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Total PWM Period</td>
                <td>9</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">EMF Feedback Cut out</td>
                <td>10</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Decoder Lock</td>
                <td>15</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Decoder Lock</td>
                <td>16</td>
                <td>Yes</td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Consist Adrress</td>
                <td>19</td>
                <td></td>
                <td></td>
            </tr>

            <tr id="LocoRow-A">
                <td data-tooltip="">Decoder Configurations</td>
                <td>29</td>
                <td>Yes</td>
                <td></td>
            </tr>

        </tbody>
    </table>
</div>

WebSite/Areas/Trains/Views/Dcc/_DccDecoder.cshtml
@model WebSite.ViewModels.DccDecoderVM

<h4>@Model.title</h4>

<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12" >
        <div class="panel panel-default">
            <div class="panel-heading">Technical Specification</div>
            <div class="panel-body">
                <table style="width:100%">
                    <tr style="padding:10px; width:60%;">
                        <td>Number of Functions</td>
                        <td>@Model.decoderDetails.numberOfFunctions</td>
                    </tr>
                    <tr style="padding:10px; width:60%;">
                        <td>Maximum Current</td>
                        <td>1 A</td>
                    </tr>
                    <tr>
                        <td>Continous Total Current</td>
                        <td>500mA</td>
                    </tr>
                    <tr>
                        <td>Maximum Motor Current</td>
                        <td>1 A</td>
                    </tr>
                    <tr>
                        <td>Function(s) output Current</td>
                        <td>100mA each</td>
                    </tr>
                    <tr style="vertical-align:top;">
                        <td>Address range</td>
                        <td>CV 1 1-127<br />CV 17-18 1-9999</td>
                    </tr>
                    <tr>
                        <td>Speed steps (selectable)</td>
                        <td>14,28,128</td>
                    </tr>
                    <tr>
                        <td>Form factor</td>
                        <td>@Model.decoderDetails.formFactor</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12" >
        <div class="panel panel-default">
            <div class="panel-heading p">Features</div>
            <div class="panel-body">
                <p style="font:bold">
                Reset to factory defaults, Write 8 to CV 8.<br />
                Can be programmed in Operating Mode, Register
                CV Mode, Paged CV Mode and Direct CV Mode.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Supported CVs</div>
            <div class="panel-body">
                <!-- loop in razor, cv details for decoder -->
                <table style="width:100%">
                    @{
                        foreach (var detail in Model.cvDetails)
                        {
                            <tr>
                                <td>@detail.CV </td>
                                <td>@detail.Description</td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    </div>
</div>