WebSite/Areas/Max4Sims/Controllers/CollectionsController.cs
using System.Web.Mvc;

using WebSite.Areas.Max4Sims.ViewModels;
using WebSite.Domain.DataTransferObjects;

namespace WebSite.Areas.Max4Sims.Controllers
{
    public class CollectionsController : Controller
    {
        public ActionResult Index() { return View(); }

        public ActionResult Fish() { return View(); }

        public ActionResult Plants() { return View(); }

        public ActionResult Frogs() { return View(); }

        public ActionResult MicroscopePrints() { return View(); }

        public ActionResult Postcards() { return View(); }

        public ActionResult SpacePrints() { return View(); }

        public ActionResult SnowGlobes() {

            SnowGlobesVM snowGlobesVM = new SnowGlobesVM();
            snowGlobesVM.SnowGlobes = new System.Collections.Generic.List<SnowGlobeVM>();

            var SnowGlobesDTO = new BusinessLogic.SnowGlobes().GetAll();

            foreach ( SnowGlobeDTO dto in SnowGlobesDTO.ListOf)
            {
                snowGlobesVM.SnowGlobes.Add(new SnowGlobeVM() { Name = dto.Name, Comments = dto.Comments, Rarity = dto.Rarity });
            }

            return View(snowGlobesVM);
        }

        public ActionResult Fossils()
        {
            FossilsVM fossilsVM = new FossilsVM();
            fossilsVM.Fossils = new System.Collections.Generic.List<FossilVM>();

            var fossilsDTO = new BusinessLogic.Fossil().GetAll();

            foreach (FossilDTO dto in fossilsDTO.ListOf)
            {
                fossilsVM.Fossils.Add(new FossilVM() { Name = dto.Name, Comments = dto.Comments, Rarity = dto.Rarity });
            }

            return View(fossilsVM);
        }
    }
}

WebSite/Areas/Max4Sims/Views/Collections/Fish.cshtml
@{
    ViewBag.Title = "Fish";
}

<style>
    .heading {
        font-weight: bold;
        text-align: center;
        text-transform: capitalize;
        width: 16.5%;
        height: 42px;
        background-color: blanchedalmond;
    }

    #tablefish {
    }

        #tablefish td {
            text-align: center;
        }
</style>

<div class="container">
    <div class="page-header">
        <h1>Fish</h1>
    </div>
    <table id="tablefish" class="table table-bordered table-condensed">
    <tr>
        <td class="heading" style="width:20%;">fish</td>
        <td class="heading" style="width:11%;">willow creek pond</td>
        <td class="heading" style="width:11%;">oasis springs pond</td>
        <td class="heading" style="width:11%;">willow creek rivers</td>
        <td class="heading" style="width:11%;">oasis springs rivers</td>
        <td class="heading" style="width:11%;">oasis springs back pond</td>
        <td class="heading" style="width:11%;">forgotten grotto</td>
        <td class="heading" style="width:13%;">sylvan glade<br />[p] pond [w]waterfall</td>
    </tr>

    <tr>
        <td>Guppy</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>

    <tr>
        <td>Perch</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>

    <tr>
        <td>Tetra</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td>w</td>
    </tr>

    <tr>
        <td>Bass</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td></td>
    </tr>

    <tr>
        <td>Minnow</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td></td>
    </tr>

    <tr>
        <td>Goldfish</td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>

    <tr>
        <td>Koi</td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>p</td>
    </tr>

    <tr>
        <td>Trout</td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>w</td>
    </tr>

    <tr>
        <td>Salmon</td>
        <td></td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td>p</td>
    </tr>

    <tr>
        <td>Kissing Gourami</td>
        <td></td>
        <td></td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>

    <tr>
        <td>Angelfish</td>
        <td></td>
        <td></td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>

    <tr>
        <td>Catfish</td>
        <td></td>
        <td></td>
        <td>x</td>
        <td>x</td>
        <td>x</td>
        <td></td>
        <td></td>
    </tr>


    <tr>
        <td>Sturgeon</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td>x</td>
        <td>w</td>
    </tr>
    <tr>
        <td>Piranha</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Betta</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td></td>
        <td>p w</td>
    </tr>
    <tr>
        <td>Red-Tailed<br />Black Shark</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Rainbowfish</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td></td>
    </tr>
    <tr>
        <td>Batfish</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td></td>
    </tr>
    <tr>
        <td>Anglerfish</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td></td>
    </tr>
    <tr>
        <td>Wolf Eel</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>x</td>
        <td></td>
    </tr>
    <tr>
        <td>Treefish</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>w</td>
    </tr>
    <tr>
        <td>Tilapia</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>w</td>
    </tr>
</table>
</div>

WebSite/Areas/Max4Sims/Views/Collections/Fossils.cshtml
@{
    ViewBag.Title = "Fossils";
}
@using WebSite.Areas.Max4Sims.ViewModels;

@model WebSite.Areas.Max4Sims.ViewModels.FossilsVM

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>@ViewBag.Title</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            @Html.Partial("_Collections")
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">

            <table class="table table-bordered table-condensed table-striped">
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Rarity</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (FossilVM fossils in Model.Fossils) {
                        <tr>
                            <td>@fossils.Name</td>
                            <td>@fossils.Rarity</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

WebSite/Areas/Max4Sims/Views/Collections/Frogs.cshtml
@{
    ViewBag.Title = "Frogs";
}

<style>
    .heading {
        font-weight: bold;
        width: 16.5%;
        height: 42px;
        background-color: blanchedalmond;
    }

    .common {
        color: blue;
    }

    .uncommon {
        color: darkorange;
    }

    .rare {
        color: darkmagenta;
    }
</style>

<script>

    $(document).ready(function () {

        $("tr#frogs td").click(function (e) {

            if ($(this).css("font-weight") == "400" ) {
                $(this).append('<span style="color:green;"> ✔ </span>');
                $(this).css("font-weight", "bold");
            }
            else
            {
                var strg = $(this).html();
                $(this).empty().append(strg.split("<")[0]);
                $(this).css("font-weight", "normal");
            }
            e.stopPropagation();

        });

    })

</script>

<div class="container">
    <div class="page-header">
        <h1>Frogs</h1>
    </div>

    <div class="row">

        <div class="col-lg-12">

            <!-- use table as data sort -->

            <div>
                <span class="pull-right" style="font-size:x-small">
                    key :&nbsp;
                    <span class="common">common</span>,
                    <span class="uncommon">uncommon</span>,
                    <span class="rare">rare</span>
                </span>
            </div>

            <table id="TableFrogs" class="table table-bordered" style="width: 100%;text-align:center">
                <tr id="frogs">
                    <td class="heading"></td>
                    <td class="heading">Normal</td>
                    <td class="heading">Striped</td>
                    <td class="heading">Spotted</td>
                    <td class="heading">Surf</td>
                    <td class="heading">Whirl</td>
                </tr>
                <tr id="frogs">
                    <td class="heading">Leaf</td>
                    <td class="common">Leaf</td>
                    <td class="common">Striped Leaf</td>
                    <td class="common">Spotted Leaf</td>
                    <td class="uncommon">Surfer Leaf</td>
                    <td class="uncommon">Hypno</td>
                </tr>
                <tr id="frogs">
                    <td class="heading">Dirt</td>
                    <td class="common">Dirt</td>
                    <td class="common">Striped Dirt&nbsp;</td>
                    <td class="common">Spotted Dirt&nbsp;</td>
                    <td class="uncommon">Dirtsurfer&nbsp;</td>
                    <td class="uncommon">Dirtwhirl&nbsp;</td>
                </tr>
                <tr id="frogs">
                    <td class="heading">Eggplant</td>
                    <td class="common">Eggplant</td>
                    <td class="uncommon">Striped Eggplant&nbsp;</td>
                    <td class="uncommon">Spotted Eggplant&nbsp;</td>
                    <td class="rare">Surfer Eggplant&nbsp;</td>
                    <td class="rare">Eggplant Whirl&nbsp;</td>
                </tr>
                <tr id="frogs">
                    <td class="heading">Heart</td>
                    <td class="common">Heart</td>
                    <td class="uncommon">Striped Heart&nbsp;</td>
                    <td class="uncommon">Spotted Heart&nbsp;</td>
                    <td class="rare">Heart Surfer&nbsp;</td>
                    <td class="rare">Bullseye&nbsp;</td>
                </tr>
                <tr id="frogs">
                    <td class="heading">Sunflower</td>
                    <td class="uncommon">Sunflower</td>
                    <td class="uncommon">Tiger&nbsp;</td>
                    <td class="uncommon">Leopard&nbsp;</td>
                    <td class="rare">Sunsurfer&nbsp;</td>
                    <td class="rare">Whirlyflower</td>
                </tr>
            </table>

        </div>
        <!--<div class="col-lg-12">
            <input id="ButtonReset" type="button" value="Reset" class="btn" onclick="frogsReset();" />
        </div>-->

    </div>

</div>

WebSite/Areas/Max4Sims/Views/Collections/MicroscopePrints.cshtml
@{
    ViewBag.Title = "Microscope Prints";
}

<div class="container">
    <div class="page-header">
        <h1>Microscope Prints</h1>
    </div>

    <div class="row">
        <div class="col-lg-2 col-sm-12">
            @Html.Partial("_Collections")
        </div>
        <div class="col-lg-6 col-sm-12">
            <h4>Regular</h4>

            <table class="table table-bordered table-condensed">
                <tr class="tableRow">
                    <td>Hooplankton</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Party in Pink</td>
                    <td>Common</td>
                </tr>
                <tr class="tableRow">
                    <td>Psychedelic Rock</td>
                    <td>Common</td>
                </tr>
                <tr class="tableRow">
                    <td>The Drifter</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Cell Block</td>
                    <td>Uncommon</td>
                </tr>
                <tr class="tableRow">
                    <td>Falling</td>
                    <td>Uncommon</td>
                </tr>
            </table>

            <h4>Plant</h4>

            <table class="table table-bordered table-condensed">
                <tr class="tableRow">
                    <td style="width:60%;">Rhapsody in Blue</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Blemish Blossom</td>
                    <td>Common</td>
                </tr>
            </table>

            <h4>Crystal</h4>

            <table class="table table-bordered table-condensed">
                <tr class="tableRow">
                    <td style="width:60%;">Snow Fight</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Crystal Palace</td>
                    <td>Rare</td>
                </tr>
            </table>

            <h4>Fossil</h4>

            <table class="table table-bordered table-condensed">
                <tr class="tableRow">
                    <td style="width:60%;">Trace Remains</td>
                    <td>Uncommon</td>
                </tr>
                <tr>
                    <td>Leaf Meat</td>
                    <td>Rare</td>
                </tr>
            </table>
        </div>
    </div>
 </div>

WebSite/Areas/Max4Sims/Views/Collections/Plants.cshtml
@{
    ViewBag.Title = "Plants";
}

<div class="container">
    <div class="page-header">
        <h1>Plants</h1>
    </div>

    <div class="row">

        <div class="col-lg-12">
            <h4>Spliced Plants</h4>

            <table style="width: 50%;" class="table table-bordered table-condensed">
                <tr class="tableRow">
                    <td>Bird of Paradise (36)</td>
                    <td>Tulip + Chrysanthemum</td>
                </tr>
                <tr>
                    <td>Bonsai Bush (24)</td>
                    <td>Daisy + Strawberry</td>
                </tr>
                <tr class="tableRow">
                    <td>Cow Berry (24)</td>
                    <td>Dragon Fruit + Snapdragon</td>
                </tr>
                <tr>
                    <td>Death Flower (48)</td>
                    <td>Orchid + Pomegranate</td>
                </tr>
                <tr class="tableRow">
                    <td>Dragon Fruit (96)</td>
                    <td>Strawberry + Snapdragon</td>
                </tr>
                <tr>
                    <td>Orchid (36)</td>
                    <td>Lily + Snapdragon</td>
                </tr>
                <tr class="tableRow">
                    <td>Pomegranate (72)</td>
                    <td>Apple + Cherry</td>
                </tr>
            </table>
        </div>

    </div>

    <div class="row">
        <div class="col-md-12">
            <p>
                Trash fruit grows from trash pile. (24)<br />
                UFO (Intergalactic growth pod) obtained from space adventure in rocket. (112)
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h4>Seed Packet</h4>
        </div>
    </div>

    <table style="width: 50%;" class="table table-bordered table-condensed table-hover">
        <tr>
            <th class="heading">Flowers</th>
            <th class="heading">Fruits</th>
            <th class="heading">Herbs</th>
            <th class="heading">Vegetables</th>
        </tr>
        <tr>
            <td>Bluebells (36)</td>
            <td>Apple (36)</td>
            <td>Basil (24)</td>
            <td>Carrot (24)</td>
        </tr>
        <tr class="tableRow">
            <td>Chrysanthemum (36)</td>
            <td>Grapes (48)</td>
            <td>Parsley (24)</td>
            <td>Mushroom (24)</td>
        </tr>
        <tr>
            <td>Daisy (24)</td>
            <td>Plantain (72)</td>
            <td>&nbsp;</td>
            <td>Spinach (24)</td>
        </tr>
    </table>

    <div class="row">
        <div class="col-md-12">
            <h4>Willow Creek</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p>
                Snapdragon (36),
                Lilly (36),
                Strawberry (24),
                Pear (60),
                Potato (24),
                Rose (48),
                Onion (48)
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h4>Oasis Springs</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p>
                Lemon (60),
                Sage (24),
                Cherry (60),
                Tomato (24),
                Tulip (36),
                Blackberry (96),
                Onion (48)
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h4>Outdoor Retreat Herbs (used for the Herbalism skill)</h4>
        </div>
    </div>

    <table style="width: 50%;" class="table table-bordered table-condensed table-hover">
        <tr>
            <th class="heading">Normal</th>
            <th class="heading">Toxic</th>
            <th class="heading">Emotion when<br />toxic form eaten</th>
        </tr>
        <tr>
            <td>Chamomile (24)</td>
            <td>Toxic Chamomile (24)</td>
            <td>Tense (2h)</td>
        </tr>
        <tr class="tableRow">
            <td>Elderberry (18)</td>
            <td>Noxious Elderberry (18)</td>
            <td>Sad (2h)</td>
        </tr>
        <tr>
            <td>Huckleberry (18)</td>
            <td>Muckleberry (18)</td>
            <td>Dazed (2h)</td>
        </tr>
        <tr class="tableRow">
            <td>Fireleaf (18)</td>
            <td>Poison Fireleaf (18)</td>
            <td>Angry (2h)</td>
        </tr>
        <tr>
            <td>Morel Mushroom (24)</td>
            <td>False Morel Mushroom (24)</td>
            <td>Uncomfortable (2h)</td>
        </tr>
    </table>

    <div class="row">
        <div class="col-md-12">
            <p>
                The herbs can be found in Granite Falls National Park.<br />
                The Morel Mushroom is only found in the hidden area of Granite falls.
            </p>
        </div>
    </div>


</div>

WebSite/Areas/Max4Sims/Views/Collections/Postcards.cshtml
@{
    ViewBag.Title = "Postcards";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>Postcards</h1>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-2 col-sm-12">
            @Html.Partial("_Collections")
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <table class="table table-bordered table-condensed">
                <tr class="tableRow">
                    <td style="width:60%;">Appaloosa Plains</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Bridgeprort</td>
                    <td>Common</td>
                </tr>
                <tr class="tableRow">
                    <td>Littlehaven</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Lucky Palms</td>
                    <td>Common</td>
                </tr>
                <tr class="tableRow">
                    <td>Moonlight Falls</td>
                    <td>Common</td>
                </tr>
                <tr class="tableRow">
                    <td>Riverview</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Sunset Valley</td>
                    <td>Common</td>
                </tr>
                <tr class="tableRow">
                    <td>Twinbrook</td>
                    <td>Common</td>
                </tr>
                <tr>
                    <td>Barnacle Bay</td>
                    <td>Uncommon</td>
                </tr>
                <tr class="tableRow">
                    <td>Champs Les Sims</td>
                    <td>Uncommon</td>
                </tr>
                <tr>
                    <td>Lunar Lakes</td>
                    <td>Uncommon</td>
                </tr>
                <tr class="tableRow">
                    <td>Midnight Hollow</td>
                    <td>Uncommon</td>
                </tr>
                <tr>
                    <td>Dragon Valley</td>
                    <td>Rare</td>
                </tr>
                <tr class="tableRow">
                    <td>Isla Paradiso</td>
                    <td>Rare</td>
                </tr>
            </table>
        </div>

    </div>
 </div>

WebSite/Areas/Max4Sims/Views/Collections/SnowGlobes.cshtml
@{
    ViewBag.Title = "Snow Globes";
}
@using System.Collections.Generic;

@model WebSite.Areas.Max4Sims.ViewModels.SnowGlobesVM

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>Snow Globes</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            @Html.Partial("_Collections")
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">

            <table class="table table-bordered table-condensed table-striped">
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Rarity</td>
                        <td>Comments</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (WebSite.Areas.Max4Sims.ViewModels.SnowGlobeVM snowGlobe in Model.SnowGlobes) {
                        <tr>
                            <td>@snowGlobe.Name</td>
                            <td>@snowGlobe.Rarity</td>
                            <td>@snowGlobe.Comments</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

WebSite/Areas/Max4Sims/Views/Collections/SpacePrints.cshtml
@{
    ViewBag.Title = "Space Prints";
}

<div class="container">
    <div class="page-header">
        <h1>Space Prints</h1>
    </div>

    <div class="row">
        <div class="col-lg-2 col-sm-12">
            @Html.Partial("_Collections")
        </div>
        <div class="col-lg-10 col-sm-12">

            <div class="col-lg-12">
                <h4>Observe the sky</h4>

                <table style="width: 50%;" class="table table-bordered table-condensed">
                    <tr class="tableRow">
                        <td style="width:60%;">Animals Planet</td>
                        <td>Common</td>
                    </tr>
                    <tr>
                        <td>Out of this world</td>
                        <td>Common</td>
                    </tr>
                    <tr class="tableRow">
                        <td>Seeing Red</td>
                        <td>Common</td>
                    </tr>
                    <tr>
                        <td>I Dream of Pleiosaur</td>
                        <td>Uncommon</td>
                    </tr>
                    <tr class="tableRow">
                        <td>Star Crossed Lovers</td>
                        <td>Uncommon</td>
                    </tr>
                </table>
            </div>

            <div class="col-lg-12">
                <h4>Stargaze</h4>

                <table style="width: 50%;" class="table table-bordered table-condensed">
                    <tr class="tableRow" ">
                        <td style="width:60%;">Big Star</td>
                        <td>Common</td>
                    </tr>
                    <tr>
                        <td>End of Time</td>
                        <td>Common</td>
                    </tr>
                    <tr class="tableRow">
                        <td>Rosie the Riveting</td>
                        <td>Common</td>
                    </tr>
                    <tr>
                        <td>Standard Space</td>
                        <td>Common</td>
                    </tr>
                    <tr class="tableRow">
                        <td>Saturn Return</td>
                        <td>Uncommon</td>
                    </tr>
                    <tr>
                        <td>Twinkle</td>
                        <td>Uncommon</td>
                    </tr>
                    <tr class="tableRow">
                        <td>T-Rex Nebula</td>
                        <td>Rare</td>
                    </tr>
                </table>
            </div>

            <div class="col-lg-12">
                <h4>Search for the Truth</h4>

                <table style="width: 50%;" class="table table-bordered table-condensed">
                    <tr class="tableRow">
                        <td style="width:60%;">Cloudy Vision</td>
                        <td>Uncommon</td>
                    </tr>
                    <tr>
                        <td>Battle Stars</td>
                        <td>Rare</td>
                    </tr>
                    <tr class="tableRow">
                        <td>Surfacing</td>
                        <td>Rare</td>
                    </tr>
                </table>
            </div>

        </div>
    </div>

 </div>

WebSite/Areas/Max4Sims/Views/Collections/_collections.cshtml
    <h4>Collections</h4>
    <ul>
        <li>@Html.ActionLink("Microscope Prints", "MicroscopePrints", "Collections")</li>
        <li>@Html.ActionLink("Postcards", "Postcards", "Collections")</li>
        <li>@Html.ActionLink("Snow Globes", "SnowGlobes", "Collections")</li>
        <li>@Html.ActionLink("Space Prints", "SpacePrints", "Collections")</li>
        <li>@Html.ActionLink("Fossils", "Fossils", "Collections")</li>
    </ul>
    <br />